print("Senior Project Developer Profile")
print()
print("Name: Maeva Innocent")
print("Major: Computer Science")
print("Technology Interest: Artificial Intelligence")
print("Skill Goal: Project Management")